version: 1

formatters:
  default:
    format: '%(asctime)s [%(levelname)-8s]: %(filename)s %(name)s  %(message)s'

handlers:
  default:
    class: logging.StreamHandler
    formatter: default

  stderr:
    class: logging.StreamHandler

  stdout:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    filename: logs/tgnews.log
    mode: w
    formatter: default

loggers:
  db_connection:
    level: DEBUG
    handlers: [file]

  __main__:
    level: INFO
    handlers: [default]

root:
  formatter: default
  handlers: [file]