version: 1

formatters:
  default:
    format: '%(asctime)s [%(levelname)-8s]: %(name)s  %(message)s'

handlers:
  default:
    class: logging.StreamHandler
    formatter: default

  stderr:
    class: logging.StreamHandler

  stdout:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    filename: logs/tgnews.log
    mode: w
    formatter: default

loggers:
  aiogram_bot:
    level: INFO
    handlers: [file]
    propagate: false

  telethon_client:
    level: INFO
    handlers: [file, default]
    propagate: false

  helpers:
    level: INFO
    handlers: [ file, default ]
    propagate: false

  database.db_connection:
    level: INFO
    handlers: [default]
    propagate: false

  __main__:
    level: DEBUG
    handlers: [default]
    propagate: false

root:
  formatter: default
  handlers: [file]